HabitTracker.Common/Controllers/HabitController.cs
using HabitTracker.DAL.Repository.IRepository;
using HabitTracker.Domain.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HabitTracker.Common.Controllers
{
    [Authorize]
    public class HabitController : Controller
    {
        private readonly IHabitRepository _habitRepository;

        public HabitController(IHabitRepository habitRepository)
        {
            _habitRepository = habitRepository;
        }

        public async Task<IActionResult> Index()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var habitsList = await _habitRepository.GetListHabitByUserIdAsync(id);
            ResetCount(habitsList);
            return View(habitsList);
        }

        //GET - CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Habit habit)
        {
            if (ModelState.IsValid)
            {
                var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                habit.ApplicationUserId = id;
                habit.NextReset = DateTime.Now.AddDays(7 - (int)DateTime.Now.DayOfWeek);
                await _habitRepository.CreateAsync(habit);
                return RedirectToAction("Index");
            }

            return View(habit);
        }

        //GET - TRACK
        public async Task<IActionResult> Track(int? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return NotFound();
            }

            Habit habit = await _habitRepository.GetByIdAsync(id.GetValueOrDefault());

            if (habit == null)
            {
                return NotFound();
            }

            IncrementCurrentCount(habit);
            CheckGoalMet(habit);

            await _habitRepository.UpdateAsync(habit);

            return RedirectToAction("Index");
        }

        private void IncrementCurrentCount(Habit habit)
        {
            habit.CurrentCount++;
        }

        private void CheckGoalMet(Habit habit)
        {
            if (habit.CurrentCount >= habit.WeeklyGoal)
            {
                habit.IsGoalMet = true;
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return NotFound();
            }

            Habit habit = await _habitRepository.GetByIdAsync(id.Value);

            if (habit == null)
            {
                return NotFound();
            }

            return View(habit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Habit habit)
        {
            if (ModelState.IsValid)
            {
                var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                habit.ApplicationUserId = id;
                await _habitRepository.UpdateAsync(habit);
                return RedirectToAction("Index");
            }
            return View(habit);
        }

        //GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return NotFound();
            }

            Habit habit = await _habitRepository.GetByIdAsync(id.Value);

            if (habit == null)
            {
                return NotFound();
            }

            return View(habit);
        }

        //POST - DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (!id.HasValue || id.Value <= 0)
            {
                return NotFound();
            }

            Habit habitToDelete = await _habitRepository.GetByIdAsync(id.Value);

            if (habitToDelete == null)
            {
                return NotFound();
            }

            await _habitRepository.DeleteAsync(habitToDelete.Id);

            return RedirectToAction("Index");
        }

        public async void ResetCount(IEnumerable<Habit> habitsList)
        {
            var date = DateTime.Today.Date;
            foreach (Habit habit in habitsList)
            {
                if (DateTime.Compare(date, habit.NextReset) >= 0)
                {
                    habit.NextReset = DateTime.Now.AddDays(7 - (int)date.DayOfWeek);
                    habit.CurrentCount = 0;
                    await _habitRepository.UpdateAsync(habit);
                }
            }
        }
    }
}

HabitTracker.Common/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HabitTracker.Common</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HabitTracker.Common.styles.css" asp-append-version="true" />
</head>
<body class="bg-light">
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom box-shadow mb-3">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Toggle button -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/images/HabitTracker.png" width="40px" height="40px" />
                    </a>
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Habit" asp-action="Index">Habits</a>
                        </li>
                    </ul>
                    <!-- Left links -->
                </div>

                <!-- Collapsible wrapper -->
                <!-- Right elements -->
                <div class="d-flex align-items-center">
                    <partial name="_LoginPartial" />
                    <a class="d-flex align-items-center hidden-arrow"
                       href="https://github.com/WTFMontag/HabitTracker"
                       id="navbarDropdownMenuAvatar"
                       aria-expanded="false">
                        <img src="~/images/GitHub-logo.png"
                             height="35"
                             alt="Default Avatar"
                             loading="lazy" />
                    </a>
                    <!-- Right elements -->
                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>